# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_logo', models.CharField(max_length=200)),
                ('school_address', models.CharField(max_length=500)),
                ('school_city', models.CharField(max_length=100)),
                ('school_state', models.CharField(max_length=100)),
                ('school_zip', models.CharField(max_length=100)),
                ('school_phone', models.CharField(max_length=200)),
                ('school_principal', models.CharField(max_length=200)),
                ('school_website', models.CharField(max_length=200)),
                ('school_short_name', models.CharField(max_length=100)),
                ('school_number', models.CharField(max_length=200)),
                ('school_base_grading_scale', models.CharField(max_length=200)),
                ('school_number_of_days_rotation', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
